= DynamoDB Stream Listener and Notifier

== Overview

This is a simple implementation of listening of DynamoDB events and notifying using the `notifiermodel.Notifier` not process filters/selections and targets (as usual).

This allows for a more fault tolerant usage of dynamodb as persistence and notify of e.g. _SQS_ targets of changes. If it fails, it will re-process the event and retry sending to target.

== Lambda

Use the lambda in production to listen on the stream and notify the targets. Just deploy the processor as lambda and call `Processor.Start` to start listen for incoming events.

== Local/Server Model

It is possible to manually poll the stream and process the events. This is still a work in progress since it needs to be tighten up in order to not re-process the same records if it fails (in some occasions).

However, if this is tolerable, it is possible to deploy it on your local machine or on a server/container to process the events. It will automatically discover new shards and handle merge/split of shards and poll those for records.

It is also possible to query for the shard states to be persisted and re-used if the process is restarted.

== TODO

* Better error handling so processed records are not re-processed as today (in Handler record loop).

== Example

This sample can be run on a local machine that expects a empty table and then the insert is captured and sent to a function that emulates e.g. a _SQS_ target.

.Example Processor Test
[source,go]
----
func TestReceiveOneEvent(t *testing.T) {
	// DynamoDB test utility
	tr := dynamodbutils.NewTestTableResource(context.Background(), TestTableName)
	defer tr.Dispose(context.Background(), dynamodbutils.DisposeOpts{DeleteItems: true})

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	var (
		oldImage, newImage *PersistenceObject
		pcError            error
		wg                 sync.WaitGroup
		res                []notifiermodel.NotificationTargetResult
	)

	processor, err := NewProcessorBuilder().
		WithTypeRegistry(types.NewRegistry().
			RegisterResolver(
				model.NewResolveFunc(
					func(id, name string) (model.TypeEntry, bool) {
						return model.TypeEntry{
							Model: reflect.TypeOf(&TestModel{}), Name: "homeHub"}, true
					},
				),
			)).
		WithStartDoneFunc(func(ctx context.Context, err error) {
			wg.Done() // signal that the processor is done
		}).
		WithEventModel(ProcessorEventModelManualAttach).
		WithStreamBuilder(
			stream.NewStreamBuilder().
				WithTable(TestTableName).
				UseClient(tr.Client).
				WithShardIteratorType(streamTypes.ShardIteratorTypeLatest),
		).
		WithCallbackProcessorCallback().
		WithProcessImageCallback(func(ctx context.Context, oldImg, newImg *PersistenceObject, err error) error {
			oldImage = oldImg
			newImage = newImg
			pcError = err

			return nil
		}).
		WithNotificationManager(notify.NewBuilder().
			TargetBuilder(
				notifiermodel.FuncTarget(
					func(
						ctx context.Context, target notifiermodel.NotificationTarget,
						tx *persistencemodel.TransactionImpl, operation ...notifiermodel.NotifierOperation,
					) []notifiermodel.NotificationTargetResult {
						// Target could e.g. be SQS, SNS, Email, SMS, etc.
						for _, op := range operation {
							res = append(res, notifiermodel.NotificationTargetResult{
								Operation: op,
								Target:    target,
								Custom:    map[string]any{"pass": true},
							})
						}

						return res
					})).
			WithSelectionBuilder(
				notifiermodel.NewSelectionBuilder(
					notifiermodel.FuncSelection(
						func(op notifiermodel.NotifierOperation, value bool) (bool, []notifiermodel.SelectedValue) {
							return true, nil // always include
						})),
			).
			Build().
			Build()).
		Build()

	require.NoError(t, err)

	err = processor.Start(ctx, true /*async*/)
	require.NoError(t, err)

	time.Sleep(5 * time.Second) // wait for the processor to start

	// Write a PK: DS#{id}, SK: DSR#{name} item using the persistence object
	// to simulate a new reported state for a manager (would be done in
	// dynamodbpersistence package in real life)
	reported := PersistenceObject{
		Version:     1,
		TimeStamp:   time.Now().Unix(),
		ClientToken: "clientToken",
		Reported: &TestModel{
			TimeZone: tz,
			Sensors: map[string]Sensor{
				"temperature": {Value: 23.4, TimeStamp: time.Now()},
			},
		},
	}

	item, err := attributevalue.MarshalMap(reported)
	require.NoError(t, err)

	item["PK"] = &ddbtypes.AttributeValueMemberS{Value: "DS#myDevice-123"}
	item["SK"] = &ddbtypes.AttributeValueMemberS{Value: "DSR#homeHub"}

	wg.Add(1)

	_, err = tr.Client.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: aws.String(TestTableName),
		Item:      item,
	})
	require.NoError(t, err)

	wg.Wait() // wait for the processor to finish

	require.NoError(t, pcError)
	require.Nil(t, oldImage)
	require.NotNil(t, newImage)
	assert.Equal(t, DynamoDbEventTypeInsert, newImage.EventType())
	assert.Len(t, res, 1)
}
----

The above sample uses a unit test class that is able to create a table and wait until it is active.