= Go Device Shadow (godeviceshadow)
This is an implementation of a device shadow storage and notification for DynamoDB and SQS/SNS. It is pluggable for other storage/notifications.

== Introduction

This is a somewhat emulation of the existing IoT Core Device Shadow. However, it separates the _Reported_ and _Desired_ states into two different sort keys to allow for more data and better querying.

The partition key is the "name" of the device shadow and hence, it is possible to do advanced naming e.g. _My House#Basement#Lightning Controller_ as a _PK_. The _SK_(s) are handled by this library.

The storage is pluggable, but it comes with a DynamoDB and in-memory implementation out of the box.

When DynamoDB is used, a DynamoDB stream listener code can be registered for the table to listen for changes and notify the clients using SQS or SNS.

This is pluggable as well, but it comes with an SQS and SNS implementation out of the box.

== Device Shadow Layout

The device shadow is rather alike the IoT Core Device Shadow but with a few differences. It has split the _Reported_ and _Desired_ states into two different sort keys to allow for more data and better querying. It will not provide with any 
diff inside the shadow itself. Instead this is reported when a change has been made to the reported/desired shadow as both old, new and diff.

=== Reported State

The sort key is a single R#<name> where the name by default is _main_ but clients may have multiple sub device shadows on a single _PK_.

A sample PK, SK: _My House#Basement#Lightning Controller_, _R#main_

.Mandatory Fields in Reported State
[source,json]
----
{
  "v": "<int64 number>", // <1>
  "ts": "int32 unix32 bit second timestamp",
  "tz": "<IANA timezone>",
  "clientToken": "<arbitrary string that the last client used to update the state>"
}
----
<1> This is used to do concurrency control where the client reads the shadow, updates and then writes back with the condition that the version number is the same as when it was read. If fails, it will read it back again and retry up to _n_ times before giving up.

=== Desired State

The sort key is a single D#<name> where the name by default is _main_ but clients may have multiple sub device shadows on a single _PK_. It must match the _R#<name>_ in order to be coupled with the device shadow sub named _<name>_.

A sample PK, SK: _My House#Basement#Lightning Controller_, _D#main_

.Mandatory Fields in Desired State
[source,json]
----
{
  "v": "<int64 number>", // <1>
  "ts": "int32 unix32 bit second timestamp",
  "tz": "<IANA timezone>",
  "clientToken": "<arbitrary string that the last client used to update the state>"
}
----
<1> This is used to do concurrency control where the client reads the shadow, updates and then writes back with the condition that the version number is the same as when it was read. If fails, it will read it back again and retry up to _n_ times before giving up.

=== Notifications

When a shadow is updated, a notification is sent to the clients. This is done by the storage implementation. For example, DynamoDB, uses a _DynamoDB Stream_ listener to listen for changes and sends to target e.g. SQS or SNS (or any other implementation).

Each target registration specifies what type of plugin (e.g. SQS), attributes such as the queue name, topic name, etc.

In addition the attributes specifies what type of events to listen for:
* Report, Desired or Both
* Regexp for PK and SK combined with a'#' separator.
* Old, New, Diff (or any combination of these)

The registrations are stored as _JSON_ with the event lambda itself (for dynamodb stream). 


== Client SDK

=== Deviations

There are many deviations from the IoT Core Device Shadow. One of the most prominent is the notion of the device shadow model. It will be replaced in full every time a write is done.

=== Timestamps

The timestamps on the items in the device shadow is completely different than for the IoT Core Device Shadow. The timestamps may either be a UTC Unix32 bit timestamp (with timezone respect to the _tz_ field) or a _RFC3339_ timestamp. The _RFC3339_ timestamp may be used when the tz may differ between the different items.

The value and timestamp is clumped together and is accessed via `ValueAndTimestamp` _interface_. The underlying struct may be anything. Each item that you want to make the client handle timestamps for must implement this interface.

.Example Model
[source,go]
----
type SensorValue struct {
  ValueAndTimestamp
  Timestamp time.Time `json:"timestamp"` // <1>
  Value any `json:"value"` // <2>
}

type Building struct {
  Controller Controller `json:"controller"`
}

type Controller struct {
  ID string `json:"id"`
  Serial string `json:"serial"`
  Brand string `json:"brand,omitempty"`
  Circuits map[int]Circuit `json:"circuits,omitempty"`
}

type Circuit struct {
   Senors map[string]SensorValue `json:"sensors,omitempty"` // <3>
}
----
<1> This is the timestamp that the sensor value was read for this example, it is possible to have many different types as long as it implements the `ValueAndTimestamp` interface.
<2> For this sensor we decided the use _RFC3339_ timestamp for user readability (not efficient though). If unix timestamp use `UnixTimestamp32` or for (64 bit `UnixTimestamp64` nano resolution) instead.
<3> Here all sensor values are stored as a map with the sensor name as the key and the value as the value. The value is a struct that implements the `ValueAndTimestamp` interface. The system only handles timestamps for a certain value and ignores the rest.

=== Creating or Updating the Device Shadow
When writing to the device shadow, for example _Report_, the _SDK_ will read the whole document and marshal it to the registered model. For example `Building` it will iterate all the fields and check if they implement the `ValueAndTimestamp` interface. If they do, it will use it to check if the client model is newer than the device shadow model. If it is, the client model value will be kept, if older, the device shadow model value will be copied to the client model.

If any field is missing in the client model but present in the shadow model, it will be added to the client model. If any field is present in the client model but not in the shadow model, it will be kept (se _Deleting an Element_ for the options).

When done it will write the loaded it back conditionally on version and increment the version (atomically). This is done with an updated timestamp of `time.Now.UTC().Unix()`. If the client supplied a `ClientToken` string, it will be added to the shadow as well.

On conflict, the client will read the shadow again and redo the merge and write it back again. After _n_ times it will give up and return an conflict error.

=== Deleting an Element

When iterating merging the structures there are two modes:  _ClientIsMaster_ and  _ServerIsMaster_.

When _ClientIsMaster_ it will just check elements that are timestamped and exists on both models. If the server model value is newer, the value will be copied to the client model. Otherwise the client model will be kept as is.

If the _ServerIsMaster_ mode it will not allow the client to delete any property only, add, update or keep values are possible.

In both modes, all values that do not implement `ValueAndTimestamp` are just used as is on the client model to write the device shadow (i.e. always overwritten without any timestamp handling).

When _ServerIsMaster_ it is not possible to delete elements only add and updates are possible from the client model.

=== Desired State

This is a separate sort key and must match a _Reported_ sort key name. This is to denote the desired state and when the client wants to report a state it may also include that the _SDK_ shall load the desired state and clear it when the desired state value are the same as reported.

In this case it will need to do this in a transaction since it is two different sort keys. For DynamoDB this is done using the transaction _API_.

It is possible for a client to state that it should ignore the desired state and only report the reported state. This is done by setting the _IgnoreDesiredState_ mode instead of the default _UseDesiredState_ mode when doing reporting.