:author_name: Mario Toffia
:author_email: no.spam@please
:author: {author_name}
:email: {author_email}
:source-highlighter: highlightjs
ifndef::icons[:icons: font]
ifndef::imagesdir[:imagesdir: ../meta/assets]
:toc:
:toclevels: 3

= DynamoDB Persistence

== Overview

This `Persistence` implementation uses DynamoDB and conditionals with version to ensure consistency.

Key features:

* 💾 *DynamoDB Backend* - Uses DynamoDB as the backend storage
* 🔒 *Consistency* - Ensures data integrity with conditional writes and versioning
* 🔀 *Flexible Storage* - Supports both separate and combined storage models
* ⚛️ *Atomic Transactions* - Provides atomic transaction support
* ⚡ *Performance* - Efficient parallel processing for better throughput

NOTE: When reported and desired is stored together, the `Write` operation must receive both `Reported` and `Desired` documents, otherwise this implementation will return an error!

When stored separately, the `Write` function will store them atomically when they appear in same `Write` operation by a transaction.

== Internals

When read, it always strives to use batch reads to minimize the number of requests to DynamoDB, it will automatically split the requests into `Config.MaxReadBatchSize` (with default 100) to avoid exceeding the limit items per read request.

Writes are always upsert, i.e. either create or update. Where it guards the consistency by a version int64 that is atomically incremented each time a conditional write is successful. If the version is different, it will return a 409 (Conflict) error.

=== Write SeparateModels

When separate models, the updates are always done separately and it is possible to do a _Desired_ write without a _Reported_ (and vice versa) in the `Write` function. If both are present, it will be done in a transaction and hence it will be a atomic operation.

It will still use the version to ensure consistency, but it will be done separately for each document in the transaction  (and update it by 1 if successful - in same operation).

This is much more efficient when e.g. most of the time it is only _Reported_ that is updated and very seldom the _Desired_ model. When only one of the models are updated, it will only update that document and hence no transaction is needed just a plain conditional write.

It will parallelize the transactions to perform the writes in parallel, but it will wait for all to be done before returning. This is controlled by `Config.SeparateModels` (with default of 1).

=== Write CombinedModels

When combined models, the updates are always done together and it is not possible to do a _Desired_ write without a _Reported_ in the `Write` function. If
both are present, it will be done as a standard conditional write since both are in the same document.

It will parallelize the writes to perform the writes in parallel, but it will wait for all to be done before returning.

=== Partition Key (PK) and Sort Key (SK)

The PK, SK keys are rendered as follows:

.Outline PK and SK
[cols="1,1,4", options="header"]
|===
|PK                 |SK               |Description
|DS#{ID}            |DSR#{Name}       |Reported Model
|DS#{ID}            |DSD#{Name}       |Desired Model
|DS#{ID}            |DSC#{Name}       |Combined Reported, Desired Models
|===

Where ID is the `PersistenceID.ID` and Name is the `PersistenceID.Name`.

=== PersistenceObject

It will store the models using a `PersistenceObject` that wraps the model and adds the versioning information. Thus if separated documents,
each of them will contain handle versioning separately and the need to a transaction is required since either both are committed or none.

.PersistenceObject
[source, go]
----
type PersistenceObject struct {
	Version int64 `json:"version"` // <1>
	TimeStamp int64 `json:"timestamp"` // <2>
	ClientToken string `json:"clientToken,omitempty"` // <3>
	Desired any `json:"desired,omitempty"` // <4>
	Reported any `json:"reported,omitempty"` // <5>
}
----
<1> Version is the version of the document where the conditional upsert are based on (and atomically incremented on success).
<2> TimeStamp is the time the document was last updated (unix64 nano timestamp with UTC time).
<3> ClientToken is a unique token for the client that initiated the request. 
<4> Desired is the desired model (if such is present). Depending on how the persistence is configured, this may be stored separately from the reported model.
<5> Reported is the reported model (if such is present). Depending on how the persistence is configured, this may be stored separately from the desired model.
