= Selection Language for Notify

== Overview

The selection language uses a SQL-like syntax for specifying selection criteria. The basic format is:

```
SELECT * FROM Notification WHERE <conditions>
```

Where conditions can include:
* All conditions can be combined using: AND, OR, and parentheses for grouping
* Object conditions: 
  * obj.ID and obj.Name - can use equality (==) or regex matching (~=)
  * obj.Operation - can match operation types using IN operator
* Log conditions:
  * log.Operation - can match log operation types using IN or == operators
  * log.Path - can use regex matching (~=) 
  * log.Value - can use various operators: ==, !=, >, <, >=, <=, ~= (regex), HAS

The `HAS` operator can be used to check if a map value contains a specific key. For example, to check if a map value has a 'temp' key:
`log.Value HAS 'temp'`

Since there may be many logger entries in the expression it is possible to combine them with AND, OR. It is also possible
to use parentheses to group expressions.

Example object conditions:
```
obj.ID ~= 'myDevice-\\d+' AND obj.Name == 'myShadow'
```

The above example checks if the obj.ID matches the regex pattern 'myDevice-\\d+' and the obj.Name equals 'myShadow'.

Example object and operation conditions:
```
obj.ID ~= 'myDevice-\\d+' AND obj.Operation IN 'report','delete'
```

The above example checks if the obj.ID matches the regex pattern 'myDevice-\\d+' and the operation is either 'report' or 'delete'.

Example log conditions:
```
log.Operation IN 'add','update' AND log.Path ~= '^Sensors-.*-indoor$' AND log.Value HAS 'temp' AND log.Value > 20
```

The above example checks for add or update operations on paths matching the regex '^Sensors-.*-indoor$', where the value has a 'temp' key and that value is greater than 20.

Combined example:
```
SELECT * FROM Notification WHERE
(obj.ID ~= 'myDevice-\\d+' AND obj.Operation IN 'report','delete')
AND
(log.Operation IN 'add','update' AND log.Path ~= '^Sensors-.*-indoor$' AND log.Value > 20)
```

More complex example:
```
SELECT * FROM Notification WHERE
(obj.ID ~= 'myDevice-\\d+' AND obj.Name == 'myShadow')
AND
(
    (log.Operation IN 'add','update' AND log.Path ~= '^Sensors-.*-indoor$' AND log.Value HAS 'temp' AND log.Value > 20)
    OR
    (log.Operation == 'acknowledge')
)
```

=== Constraints & Bugs

This is a newer version of the selection language that replaces the previous toy DSL.

.Constraints Table
[cols="3,5"]
|===
| Constraint                      | Description
| Complex nested expressions      | While nested expressions are supported, extremely complex nested expressions might cause parsing issues
|===