:author_name: Mario Toffia
:author_email: no.spam@please
:author: {author_name}
:email: {author_email}
:source-highlighter: highlightjs
ifndef::icons[:icons: font]
ifndef::imagesdir[:imagesdir: ../meta/assets]
:toc:
:toclevels: 3

= Examples
Some examples how to use the library and it's functionality.

== Merge Package
This shows how to use and expect from the merge package.

=== Plain Merge

This is the `merge.Merge` function that allows for merging two models together and have one or more loggers attached to the merge operation. Two modes
of merge is possible, `merge.ServerIsMaster` and `merge.ClientIsMaster`. The first one is the default and does not allow for deletions, the latter
allows for deletions.

.Merging
[source,go]
----
func TestMerge(t *testing.T) {
  // See types.go for the structs below
  hubZero := HomeTemperatureHub{ // <1>
    DeviceShadow: DeviceShadow{
      TimeZone: "Europe/Stockholm",
      Owner:    "mariotoffia",
    },
    ClimateSensors: ClimateSensors{
      Indoor: map[string]IndoorTemperatureSensor{
        "living_room": {
          Floor:       1,
          Direction:   DirectionNorth,
          Temperature: 22.6,
          UpdatedAt:   parse("2023-01-01T10:00:00+01:00"),
          Humidity:    32.0,
        },
      },
    },
  }

  hub := HomeTemperatureHub{ // <2>
    DeviceShadow: DeviceShadow{
      TimeZone: "Europe/Stockholm",
      Owner:    "mariotoffia",
    },
    ClimateSensors: ClimateSensors{
      Outdoor: map[string]OutdoorTemperatureSensor{
        "garden": {
          Direction:   DirectionNorth,
          Temperature: -27.0,
          UpdatedAt:   parse("2023-01-01T12:00:00+01:00"),
          Humidity:    17.0,
        },
      },
      Indoor: map[string]IndoorTemperatureSensor{
        "living_room": {
          Floor:       1,
          Direction:   DirectionNorth,
          Temperature: 22.6,
          UpdatedAt:   parse("2023-01-01T11:55:00+01:00"),
          Humidity:    32.0,
        },
        "basement": {
          Floor:       0,
          Direction:   DirectionSouth,
          Temperature: 18.0,
          UpdatedAt:   parse("2023-01-01T11:00:00+01:00"),
          Humidity:    40.0,
        },
      },
    },
  }

  sl := strlogger.NewStringLogger() // <3>

  res, err := merge.Merge(hubZero, hub, merge.MergeOptions{
    Mode:    merge.ServerIsMaster,   // <4>
    Loggers: merge.MergeLoggers{sl}, // <5>
  })
  require.NoError(t, err)
  assert.Equal(t, hub, res) // <6>

  fmt.Println(sl.String())
}
----
<1> This is the baseline (e.g. gotten from _DynamoDB_)
<2> Acts as the update to the device shadow.
<3> Simple logger that logs each merge event in a single row (good for debugging)
<4> No deletion is possible only: add, update and no change are permitted (use `ClientIsMaster` to allow deletions)
<5> It is possible to have multiple merge loggers attached e.g. one to log, one to update _Amazon Aurora DSQL_ table and so on.
<6> In this case we are in sync with latest, but where there any deletes in _res_, those would not been propagated.

=== Desired & Reported Handling

This is a more complex example where we have a device shadow and a desired state. The device shadow is the reported state and the desired state is the
state we want to have. The `merge.Desired` function is used to acknowledge the reported state and remove any actuation that has been done.


.Desired & Reported Handling
[source,go]
----
func TestDesiredReported(t *testing.T) {
  reported := HomeTemperatureHub{ // <1>
    DeviceShadow: &DeviceShadow{
      TimeZone: "Europe/Stockholm",
      Owner:    "mariotoffia",
    },
    ClimateSensors: &ClimateSensors{
      Outdoor: map[string]OutdoorTemperatureSensor{
        "garden": {
          Direction:   DirectionNorth,
          Temperature: -27.0,
          UpdatedAt:   parse("2023-01-01T12:00:00+01:00"),
          Humidity:    17.0,
        },
      },
      Indoor: map[string]IndoorTemperatureSensor{
        "living_room": {
          Floor:       1,
          Direction:   DirectionNorth,
          Temperature: 22.6,
          UpdatedAt:   parse("2023-01-01T11:55:00+01:00"),
          Humidity:    32.0,
        },
        "basement": {
          Floor:       0,
          Direction:   DirectionSouth,
          Temperature: 18.0,
          UpdatedAt:   parse("2023-01-01T11:00:00+01:00"),
          Humidity:    40.0,
        },
      },
    },
  }
  
  desired := HomeTemperatureHub{} // <2>

  var err error
  
  desired, err = merge.Merge(desired, HomeTemperatureHub{ // <3>
    IndoorTempSP: &IndoorTemperatureSetPoint{
      SetPoint:  22.0,
      UpdatedAt: parse("2023-01-01T13:00:00+01:00"),
    },
  }, merge.MergeOptions{})

  require.NoError(t, err)
  require.Equal(t, 22.0, desired.IndoorTempSP.SetPoint)

  data, _ := json.Marshal(desired)
  fmt.Println(string(data))
  // Output:
  // {"indoor_temp_sp":{"sp":22,"ts":"2023-01-01T13:00:00+01:00"}}
  
  reported, err = merge.Merge(reported, HomeTemperatureHub{ // <4>
    IndoorTempSP: &IndoorTemperatureSetPoint{
      SetPoint: 22.0,      
      UpdatedAt: parse("2023-01-01T13:05:00+01:00"), // <5>
    },
  }, merge.MergeOptions{
    Mode: merge.ServerIsMaster,
  })

  data, _ = json.Marshal(reported)
  fmt.Println(string(data))
  // Output:
  // {
  //   "shadow": {"tz": "Europe/Stockholm", "owner": "mariotoffia"},
  //   "climate": {
  //     "outdoor": {
  //       "garden": {
  //         "direction": "north",
  //         "t": -27,
  //         "h": 17,
  //         "ts": "2023-01-01T12:00:00+01:00"
  //       }
  //     },
  //     "indoor": {
  //       "basement": {
  //         "floor": 0,
  //         "direction": "south",
  //         "t": 18,
  //         "h": 40,
  //         "ts": "2023-01-01T11:00:00+01:00"
  //       },
  //       "living_room": {
  //         "floor": 1,
  //         "direction": "north",
  //         "t": 22.6,
  //         "h": 32,
  //         "ts": "2023-01-01T11:55:00+01:00"
  //       }
  //     }
  //   },
  //   "indoor_temp_sp": {"sp": 22, "ts": "2023-01-01T13:05:00+01:00"}
  // }


  require.NoError(t, err)
  require.Equal(t, 22.0, reported.IndoorTempSP.SetPoint)

  desired, err = merge.Desired(reported, desired, merge.DesiredOptions{}) // <6>

  require.NoError(t, err)
  assert.Nil(t, desired.IndoorTempSP, "Is removed from desired since reported")

  data, _ = json.Marshal(desired)
  fmt.Println(string(data))
  // Output:
  // {}
}
----
<1> Initial device shadow state of the reported (e.g. from db)
<2> Initial desired state of the hub (e.g. from db)
<3> Simulate new actuation -> plain merge
<4> Report back to the device shadow
<5> Must be added or newer ts than the "old" reported, older will be ignored
<6> Acknowledge in the desired model -> removed from model

== Persistence Packages

=== Memory Persistence Store
This is a simple in-memory store that can be used for testing or small applications or serve as a in-memory cache. It is go routine safe and can handle separate and combined model persistence.

.Example Usage of Memory Store
[source,go]
----
func TestReadWrite(t *testing.T) {
  persistence := mempersistence.New(mempersistence.PersistenceOpts{
    Separation: persistencemodel.SeparateModels, // <1>
  })

  ctx := context.Background()

  writeRes := persistence.Write(ctx, // <2>
    persistencemodel.WriteOptions{},
    persistencemodel.WriteOperation{
      ID: persistencemodel.PersistenceID{
        ID: "device123", Name: "HomeHub", ModelType: persistencemodel.ModelTypeReported,
      },
      Model: map[string]IndoorTemperatureSensor{
        "temperature": {
          Floor:       1,
          Direction:   DirectionNorth,
          Temperature: 23.5,
          Humidity:    45.5,
          UpdatedAt:   time.Now(),
        },
      },
    })

  assert.Len(t, writeRes, 1)
  assert.NoError(t, writeRes[0].Error)

  res := persistence.Read(ctx, // <3>
    persistencemodel.ReadOptions{},
    persistencemodel.ReadOperation{
      ID: persistencemodel.PersistenceID{
        ID: "device123", Name: "HomeHub", ModelType: persistencemodel.ModelTypeReported,
      },
    })

  require.Len(t, res, 1)
  require.NoError(t, res[0].Error)
  assert.NotNil(t, res[0].Model)

  temp := res[0].Model.(map[string]IndoorTemperatureSensor)["temperature"]
  assert.Equal(t, 1, temp.Floor)
  assert.Equal(t, DirectionNorth, temp.Direction)
  assert.Equal(t, 23.5, temp.Temperature)
  assert.Equal(t, 45.5, temp.Humidity)

  deleteRes := persistence.Delete(ctx, // <4>
    persistencemodel.WriteOptions{},
    persistencemodel.WriteOperation{
      ID: persistencemodel.PersistenceID{
        ID: "device123", Name: "HomeHub", ModelType: persistencemodel.ModelTypeReported,
      },
    })

  assert.Len(t, deleteRes, 1)
  assert.NoError(t, deleteRes[0].Error)

  res = persistence.Read(ctx, // <5>
    persistencemodel.ReadOptions{},
    persistencemodel.ReadOperation{
      ID: persistencemodel.PersistenceID{
        ID: "device123", Name: "HomeHub", ModelType: persistencemodel.ModelTypeReported,
      },
    })

  assert.Len(t, res, 1)
  assert.Error(t, res[0].Error, "Read operation should return an error for a deleted model")
  assert.Equal(t, 404, res[0].Error.(persistencemodel.PersistenceError).Code)
}
----
<1> Use separate models for reported and desired so we just need to write one of them (otherwise it is mandatory to provide both in a write)
<2> Write a reported model into the store
<3> Read the model back from the store and it should be successful. We could specify a version, though this would required a correct version, otherwise it will return 409 (conflict) to indicate that the version is not correct. Version _0_ ignores that and just read a version.
<4> Delete the model from the store
<5> Read the model back from the store and it should return an error since it is deleted. It has the code _404_ since it is not found.

=== DynamoDB Persistence Store

This works exactly as memory store but is backed by _DynamoDB_. It uses transaction, with conditional, if separate model and simple conditional if combined model. It uses the `PersistenceID.ID` as the partition key and the `PersistenceID.Name` as the sort key. It prefixes the partition key with _DS#{PK}_ and depending on model type it prefixes the sort key with _DSR#{SK}_ (Reported) or _DSD#{SK}_ (Desired). When it is combined
the sort key is _DSC#{SK}_.

.Example Usage of DynamoDB Store
[source,go]
----
func TestReadUnversionedCombined(t *testing.T) {
  ctx := context.Background()
  res := dynamodbutils.NewTestTableResource(ctx, "MyTable") // <1>

  defer res.Dispose(ctx, dynamodbutils.DisposeOpts{DeleteItems: true})

  p, err := dynamodbpersistence.New(ctx, dynamodbpersistence.Config{
    Table:  res.Table, // <2>
    Client: res.Client, // <3>
  })
  require.NoError(t, err)

  clientID := persistutils.Id("test-")

  operations := p.Write( // <4>
    ctx,
    persistencemodel.WriteOptions{
      Config: persistencemodel.WriteConfig{
        Separation: persistencemodel.CombinedModels,
      },
    },
    persistencemodel.WriteOperation{
      ClientID: clientID,
      ID: persistencemodel.PersistenceID{
        ID: "deviceA", Name: "shadowA", ModelType: persistencemodel.ModelTypeReported,
      },
      Model: TestModel{
        TimeZone: "Europe/Stockholm",
        Sensors: map[string]Sensor{
          "temp": {Value: 21.5, TimeStamp: time.Now().UTC()},
        },
      },
    },
    persistencemodel.WriteOperation{
      ClientID: clientID,
      ID: persistencemodel.PersistenceID{
        ID: "deviceA", Name: "shadowA", ModelType: persistencemodel.ModelTypeDesired,
      },
      Model: TestModel{},
    },
  )

  require.Len(t, operations, 2)
  require.NoError(t, operations[0].Error)
  require.NoError(t, operations[1].Error)

  read := p.Read(ctx, persistencemodel.ReadOptions{}, persistencemodel.ReadOperation{ // <5>
    ID:      persistencemodel.PersistenceID{ID: "deviceA", Name: "shadowA"},
    Model:   reflect.TypeOf(&TestModel{}),
    Version: 0, /*any -> non conditional read*/
  })

  require.Len(t, read, 2)
  require.Equal(t, "deviceA", read[0].ID.ID)
  require.Equal(t, "shadowA", read[0].ID.Name)
  require.NotNil(t, read[0].Model)

  require.Equal(t, "deviceA", read[1].ID.ID)
  require.Equal(t, "shadowA", read[1].ID.Name)
  require.NotNil(t, read[1].Model)

  model, ok := read[0].Model.(*TestModel)
  require.True(t, ok)
  require.NotNil(t, model)
}
----
<1> This is a test utility that can create a table and delete it when done (if configured so)
<2> The _DynamoDB_ table to use for read, write, and query.
<3> The _DynamoDB_ client to use. If not set it will use `awsconfig.LoadDefaultConfig` to load the default configuration.
<4> Writes as combined models (i.e. one entry for reported and one for desired). Note that it has to be two write operations so it is no different from writing separate models. It is optional to set the _Separation_, if not passed it will use the `Persistence` default.
<5> Read it back. Independent on storage, it will return both reported and desired in separate results.

== Std Manager Package
This package uses persistence, merge, type registry to constitute a manager that can handle high level interactions with a model.

=== Reporting & Desired Handling
The below example shows how a client sets a desired state and at a later point in time a report that the state has been set will remove
the desired state and only the value is present in the reported state.

It also shows how to perform a plain _read_ operation to get the reported and desired states.

.Example Reporting & Desired Handling
[source,go]
----
func TestDesireReportThatAcknowledgesAndReadAgain(t *testing.T) {
  ctx := context.Background()
  now := time.Now()

  const tz = "Europe/Stockholm"

  mgr := stdmgr.New().
    WithPersistence(mempersistence.New()).
    WithSeparation(persistencemodel.CombinedModels). // <1>
    WithTypeRegistryResolver(
      types.NewRegistry().RegisterResolver( // <2>
        model.NewResolveFunc(func(id, name string) (model.TypeEntry, bool) {
          if name == "homeHub" {
            return model.TypeEntry{
              Name: "homeHub", Model: reflect.TypeOf(TestModel{}),
            }, true
          }

          return model.TypeEntry{}, false
        }),
      ),
    ).
    Build()

  resDesire := mgr.Desire(ctx, managermodel.DesireOperation{ // <3>
    ClientID: "myClient",
    Model: TestModel{
      TimeZone: tz,
      Sensors: map[string]Sensor{
        "temp": {Value: 23.4, TimeStamp: now},
      },
    },
    ID: persistencemodel.ID{ID: "device1234", Name: "homeHub"},
  })

  require.Len(t, resDesire, 1)
  require.NoError(t, resDesire[0].Error)

  resReport := mgr.Report(ctx, managermodel.ReportOperation{ // <4>
    ClientID: "myClient",
    Model: TestModel{
      TimeZone: tz,
      Sensors: map[string]Sensor{
        "temp": {Value: 23.4, TimeStamp: now},
      },
    },
    ID: persistencemodel.ID{ID: "device1234", Name: "homeHub"},
  })

  require.Len(t, resReport, 1)
  require.NoError(t, resReport[0].Error)
  assert.True(t, resReport[0].ReportedProcessed)
  assert.True(t, resReport[0].DesiredProcessed)

  resRead := mgr.Read(ctx,
    managermodel.ReadOperation{
      ID: persistencemodel.PersistenceID{ID: "device1234", Name: "homeHub", ModelType: persistencemodel.ModelTypeReported},
    },
    managermodel.ReadOperation{
      ID: persistencemodel.PersistenceID{ID: "device1234", Name: "homeHub", ModelType: persistencemodel.ModelTypeDesired},
    },
  )
  require.Len(t, resRead, 2)
  require.NoError(t, resRead[0].Error)
  require.NoError(t, resRead[1].Error)

  var desired, reported TestModel

  if resRead[0].ID.ModelType == persistencemodel.ModelTypeReported {
    reported = resRead[0].Model.(TestModel)
    desired = resRead[1].Model.(TestModel)
  } else {
    reported = resRead[1].Model.(TestModel)
    desired = resRead[0].Model.(TestModel)
  }

  assert.Len(t, desired.Sensors, 0) // <5>
  require.NotNil(t, reported.Sensors)
  require.Len(t, reported.Sensors, 1) // <6>

  assert.Equal(t, 23.4, reported.Sensors["temp"].Value)
}
----
<1> In this example, we store both reported and desired as a combined entry in the persistence.
<2> Extremely simple resolver that translates all _homeHub_ to `TestModel`.
<3> We desire temp to to be set to _23.4_, reported is still nothing.
<4> Simulates a report back that the temp has been set to _23.4_ at a later stage.
<5> Desired state is removed.
<6> Reported state is present and it is of value _23.4_.