:author_name: Mario Toffia
:author_email: no.spam@please
:author: {author_name}
:email: {author_email}
:source-highlighter: highlightjs
ifndef::icons[:icons: font]
ifndef::imagesdir[:imagesdir: ../meta/assets]
:toc:
:toclevels: 3

= Examples
Some examples how to use the library and it's functionality.

== Merge Package
This shows how to use and expect from the merge package.

.Merging
[source,go]
----
func TestMerge(t *testing.T) {
	// See types.go for the structs below
	hubZero := HomeTemperatureHub{ // <1>
		DeviceShadow: DeviceShadow{
			TimeZone: "Europe/Stockholm",
			Owner:    "mariotoffia",
		},
		ClimateSensors: ClimateSensors{
			Indoor: map[string]IndoorTemperatureSensor{
				"living_room": {
					Floor:       1,
					Direction:   DirectionNorth,
					Temperature: 22.6,
					UpdatedAt:   parse("2023-01-01T10:00:00+01:00"),
					Humidity:    32.0,
				},
			},
		},
	}

	hub := HomeTemperatureHub{ // <2>
		DeviceShadow: DeviceShadow{
			TimeZone: "Europe/Stockholm",
			Owner:    "mariotoffia",
		},
		ClimateSensors: ClimateSensors{
			Outdoor: map[string]OutdoorTemperatureSensor{
				"garden": {
					Direction:   DirectionNorth,
					Temperature: -27.0,
					UpdatedAt:   parse("2023-01-01T12:00:00+01:00"),
					Humidity:    17.0,
				},
			},
			Indoor: map[string]IndoorTemperatureSensor{
				"living_room": {
					Floor:       1,
					Direction:   DirectionNorth,
					Temperature: 22.6,
					UpdatedAt:   parse("2023-01-01T11:55:00+01:00"),
					Humidity:    32.0,
				},
				"basement": {
					Floor:       0,
					Direction:   DirectionSouth,
					Temperature: 18.0,
					UpdatedAt:   parse("2023-01-01T11:00:00+01:00"),
					Humidity:    40.0,
				},
			},
		},
	}

	sl := strlogger.NewStringLogger() // <3>

	res, err := merge.Merge(hubZero, hub, merge.MergeOptions{
		Mode:    merge.ServerIsMaster,   // <4>
		Loggers: merge.MergeLoggers{sl}, // <5>
	})
	require.NoError(t, err)
	assert.Equal(t, hub, res) // <6>

	fmt.Println(sl.String())
}
----
<1> This is the baseline (e.g. gotten from _DynamoDB_)
<2> Acts as the update to the device shadow.
<3> Simple logger that logs each merge event in a single row (good for debugging)
<4> No deletion is possible only: add, update and no change are permitted (use `ClientIsMaster` to allow deletions)
<5> It is possible to have multiple merge loggers attached e.g. one to log, one to update _Amazon Aurora DSQL_ table and so on.
<6> In this case we are in sync with latest, but where there any deletes in _res_, those would not been propagated.

.Desired & Reported Handling
[source,go]
----
func TestDesiredReported(t *testing.T) {
	reported := HomeTemperatureHub{ // <1>
		DeviceShadow: &DeviceShadow{
			TimeZone: "Europe/Stockholm",
			Owner:    "mariotoffia",
		},
		ClimateSensors: &ClimateSensors{
			Outdoor: map[string]OutdoorTemperatureSensor{
				"garden": {
					Direction:   DirectionNorth,
					Temperature: -27.0,
					UpdatedAt:   parse("2023-01-01T12:00:00+01:00"),
					Humidity:    17.0,
				},
			},
			Indoor: map[string]IndoorTemperatureSensor{
				"living_room": {
					Floor:       1,
					Direction:   DirectionNorth,
					Temperature: 22.6,
					UpdatedAt:   parse("2023-01-01T11:55:00+01:00"),
					Humidity:    32.0,
				},
				"basement": {
					Floor:       0,
					Direction:   DirectionSouth,
					Temperature: 18.0,
					UpdatedAt:   parse("2023-01-01T11:00:00+01:00"),
					Humidity:    40.0,
				},
			},
		},
	}
	
	desired := HomeTemperatureHub{} // <2>

	var err error
	
	desired, err = merge.Merge(desired, HomeTemperatureHub{ // <3>
		IndoorTempSP: &IndoorTemperatureSetPoint{
			SetPoint:  22.0,
			UpdatedAt: parse("2023-01-01T13:00:00+01:00"),
		},
	}, merge.MergeOptions{})
	require.NoError(t, err)
	require.Equal(t, 22.0, desired.IndoorTempSP.SetPoint)

	data, _ := json.Marshal(desired)
	fmt.Println(string(data))
	// Output:
	// {"indoor_temp_sp":{"sp":22,"ts":"2023-01-01T13:00:00+01:00"}}
	
	reported, err = merge.Merge(reported, HomeTemperatureHub{ // <4>
		IndoorTempSP: &IndoorTemperatureSetPoint{
			SetPoint: 22.0,			
			UpdatedAt: parse("2023-01-01T13:05:00+01:00"), // <5>
		},
	}, merge.MergeOptions{
		Mode: merge.ServerIsMaster,
	})

	data, _ = json.Marshal(reported)
	fmt.Println(string(data))
	// Output:
	// {
	//   "shadow": {"tz": "Europe/Stockholm", "owner": "mariotoffia"},
	//   "climate": {
	//     "outdoor": {
	//       "garden": {
	//         "direction": "north",
	//         "t": -27,
	//         "h": 17,
	//         "ts": "2023-01-01T12:00:00+01:00"
	//       }
	//     },
	//     "indoor": {
	//       "basement": {
	//         "floor": 0,
	//         "direction": "south",
	//         "t": 18,
	//         "h": 40,
	//         "ts": "2023-01-01T11:00:00+01:00"
	//       },
	//       "living_room": {
	//         "floor": 1,
	//         "direction": "north",
	//         "t": 22.6,
	//         "h": 32,
	//         "ts": "2023-01-01T11:55:00+01:00"
	//       }
	//     }
	//   },
	//   "indoor_temp_sp": {"sp": 22, "ts": "2023-01-01T13:05:00+01:00"}
	// }


	require.NoError(t, err)
	require.Equal(t, 22.0, reported.IndoorTempSP.SetPoint)

	desired, err = merge.Desired(reported, desired, merge.DesiredOptions{}) // <6>
	require.NoError(t, err)
	assert.Nil(t, desired.IndoorTempSP, "Is removed from desired since reported")

	data, _ = json.Marshal(desired)
	fmt.Println(string(data))
	// Output:
	// {}
}
----
<1> Initial device shadow state of the reported (e.g. from db)
<2> Initial desired state of the hub (e.g. from db)
<3> Simulate new actuation --> plain merge
<4> Report back to the device shadow
<5> Must be added or newer ts than the "old" reported, older will be ignored
<6> Acknowledge in the desired model --> removed from model